name: vit_table
description: 'Create simple yet beautiful tables'
version: 3.2.1
homepage:
repository: https://github.com/TimeLord2010/vit_table

environment:
  sdk: ^3.5.0
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  vit_dart_extensions: ^4.0.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
