name: vit_table
description: "Create a simple yet beautiful tables"
version: 1.0.1
homepage:
repository: https://github.com/TimeLord2010/vit_table

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vit_dart_extensions: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
